// 64卦数据
const HEXAGRAMS = [
            { pattern: 0b111111, num: 1, name: '乾为天', upper: '乾', lower: '乾',
                judgment: '元亨利贞', interp: '大吉之卦，如龙行天。诸事亨通，宜积极进取，但切记刚极易折，居安思危。' },
            { pattern: 0b000000, num: 2, name: '坤为地', upper: '坤', lower: '坤',
                judgment: '元亨，利牝马之贞', interp: '柔顺承载，厚德载物。宜顺势而为，以柔克刚，守静待时则吉。' },
            { pattern: 0b010001, num: 3, name: '水雷屯', upper: '坎', lower: '震',
                judgment: '元亨利贞，勿用有攸往', interp: '万物初生，艰难起步。如种子破土，宜耐心耕耘，不宜冒进。' },
            { pattern: 0b100010, num: 4, name: '山水蒙', upper: '艮', lower: '坎',
                judgment: '亨，匪我求童蒙', interp: '蒙昧待启，如幼童求学。宜虚心请教，不可自以为是，启蒙则吉。' },
            { pattern: 0b010111, num: 5, name: '水天需', upper: '坎', lower: '乾',
                judgment: '有孚，光亨，贞吉', interp: '等待时机，如云聚待雨。凡事需耐心守候，时机一到自然成。' },
            { pattern: 0b111010, num: 6, name: '天水讼', upper: '乾', lower: '坎',
                judgment: '有孚窒惕，中吉终凶', interp: '争讼之象，宜和解不宜纠缠。退一步海阔天空，见好就收。' },
            { pattern: 0b000010, num: 7, name: '地水师', upper: '坤', lower: '坎',
                judgment: '贞，丈人吉，无咎', interp: '统兵出征，需师出有名。凡事以正为先，得道多助，失道寡助。' },
            { pattern: 0b010000, num: 8, name: '水地比', upper: '坎', lower: '坤',
                judgment: '吉，原筮元永贞', interp: '亲附和合，如水流归地。人际关系和谐，宜团结协作，共同进退。' },
            { pattern: 0b110111, num: 9, name: '风天小畜', upper: '巽', lower: '乾',
                judgment: '亨，密云不雨', interp: '积蓄待发，如云聚未雨。小有积蓄但尚未大成，继续积累必有收获。' },
            { pattern: 0b111011, num: 10, name: '天泽履', upper: '乾', lower: '兑',
                judgment: '履虎尾，不咥人，亨', interp: '如履虎尾，谨慎行事。虽处险境但能化险为夷，小心驶得万年船。' },
            { pattern: 0b000111, num: 11, name: '地天泰', upper: '坤', lower: '乾',
                judgment: '小往大来，吉亨', interp: '天地交泰，万物通泰。大吉大利，时运亨通，事业顺遂，心情舒畅。' },
            { pattern: 0b111000, num: 12, name: '天地否', upper: '乾', lower: '坤',
                judgment: '否之匪人，不利君子贞', interp: '天地闭塞，万事不顺。宜韬光养晦，静待时机，不宜大动干戈。' },
            { pattern: 0b111101, num: 13, name: '天火同人', upper: '乾', lower: '离',
                judgment: '同人于野，亨', interp: '志同道合，同心协力。利于合作共赢，广结善缘，众志成城。' },
            { pattern: 0b101111, num: 14, name: '火天大有', upper: '离', lower: '乾',
                judgment: '元亨', interp: '大丰收，富足丰盈。万事亨通，如日中天，宜分享成果，广施善行。' },
            { pattern: 0b000100, num: 15, name: '地山谦', upper: '坤', lower: '艮',
                judgment: '亨，君子有终', interp: '谦虚受益，骄傲招损。满招损谦受益，保持谦逊则事事顺遂。' },
            { pattern: 0b001000, num: 16, name: '雷地豫', upper: '震', lower: '坤',
                judgment: '利建侯行师', interp: '愉悦和乐，如春雷唤醒大地。宜顺势而动，但不可过度享乐。' },
            { pattern: 0b011001, num: 17, name: '泽雷随', upper: '兑', lower: '震',
                judgment: '元亨利贞，无咎', interp: '随顺时势，灵活应变。如流水随形，随机而变则无往不利。' },
            { pattern: 0b100110, num: 18, name: '山风蛊', upper: '艮', lower: '巽',
                judgment: '元亨，利涉大川', interp: '积弊待除，拨乱反正。发现问题即需整顿，革故鼎新则吉。' },
            { pattern: 0b000011, num: 19, name: '地泽临', upper: '坤', lower: '兑',
                judgment: '元亨利贞，至于八月有凶', interp: '居高临下，亲临视察。宜深入了解情况，但须知盛极而衰。' },
            { pattern: 0b110000, num: 20, name: '风地观', upper: '巽', lower: '坤',
                judgment: '盥而不荐，有孚颙若', interp: '观察审视，如风吹大地。宜静观其变，深思熟虑后再行动。' },
            { pattern: 0b101001, num: 21, name: '火雷噬嗑', upper: '离', lower: '震',
                judgment: '亨，利用狱', interp: '咬合决断，如雷电交加。宜果断决策，排除障碍，惩治奸邪。' },
            { pattern: 0b100101, num: 22, name: '山火贲', upper: '艮', lower: '离',
                judgment: '亨，小利有攸往', interp: '文饰之美，如山间晚霞。宜注重外在修饰，但不可华而不实。' },
            { pattern: 0b100000, num: 23, name: '山地剥', upper: '艮', lower: '坤',
                judgment: '不利有攸往', interp: '剥落衰败，如山崩地裂。宜守不宜攻，等待衰极转盛之时。' },
            { pattern: 0b000001, num: 24, name: '地雷复', upper: '坤', lower: '震',
                judgment: '亨，出入无疾', interp: '一阳来复，冬去春来。衰极转盛，好运回归，万象更新。' },
            { pattern: 0b111001, num: 25, name: '天雷无妄', upper: '乾', lower: '震',
                judgment: '元亨利贞，其匪正有眚', interp: '真实无妄，不可有非分之想。顺其自然，不可强求，守正得吉。' },
            { pattern: 0b100111, num: 26, name: '山天大畜', upper: '艮', lower: '乾',
                judgment: '利贞，不家食吉', interp: '大积蓄，如高山藏宝。厚积薄发，宜努力学习积累，养精蓄锐。' },
            { pattern: 0b100001, num: 27, name: '山雷颐', upper: '艮', lower: '震',
                judgment: '贞吉，观颐自求口实', interp: '颐养之道，注意饮食和修养。宜节制欲望，修身养性。' },
            { pattern: 0b011110, num: 28, name: '泽风大过', upper: '兑', lower: '巽',
                judgment: '栋桡，利有攸往，亨', interp: '矫枉过正，如梁木弯曲。凡事过犹不及，需要适度调整。' },
            { pattern: 0b010010, num: 29, name: '坎为水', upper: '坎', lower: '坎',
                judgment: '习坎，有孚维心亨', interp: '重重险阻，如涉深水。处险不惊，保持信念，终能渡难关。' },
            { pattern: 0b101101, num: 30, name: '离为火', upper: '离', lower: '离',
                judgment: '利贞，亨，畜牝牛吉', interp: '光明依附，如火焰般炽热。宜依附正道，保持光明磊落。' },
            { pattern: 0b011100, num: 31, name: '泽山咸', upper: '兑', lower: '艮',
                judgment: '亨，利贞，取女吉', interp: '感而遂通，两情相悦。感情和合之象，恋爱婚姻大吉大利。' },
            { pattern: 0b001110, num: 32, name: '雷风恒', upper: '震', lower: '巽',
                judgment: '亨，无咎，利贞', interp: '持之以恒，如日月运行。长久之道在于坚持，守常不变则吉。' },
            { pattern: 0b111100, num: 33, name: '天山遁', upper: '乾', lower: '艮',
                judgment: '亨，小利贞', interp: '退避隐遁，以退为进。势不可为时，暂避锋芒，保全实力。' },
            { pattern: 0b001111, num: 34, name: '雷天大壮', upper: '震', lower: '乾',
                judgment: '利贞', interp: '强盛壮大，如雷霆万钧。力量充足，但不可恃强凌弱，以正行事。' },
            { pattern: 0b101000, num: 35, name: '火地晋', upper: '离', lower: '坤',
                judgment: '康侯用锡马蕃庶', interp: '蒸蒸日上，如旭日东升。事业进步，前程似锦，步步高升。' },
            { pattern: 0b000101, num: 36, name: '地火明夷', upper: '坤', lower: '离',
                judgment: '利艰贞', interp: '光明受伤，如日落西山。宜韬光养晦，忍辱负重，黑暗终将过去。' },
            { pattern: 0b110101, num: 37, name: '风火家人', upper: '巽', lower: '离',
                judgment: '利女贞', interp: '家庭和睦，如春风暖火。宜注重家庭关系，家和万事兴。' },
            { pattern: 0b101011, num: 38, name: '火泽睽', upper: '离', lower: '兑',
                judgment: '小事吉', interp: '乖离不合，求同存异。小事可成，大事难合，宜包容差异。' },
            { pattern: 0b010100, num: 39, name: '水山蹇', upper: '坎', lower: '艮',
                judgment: '利西南，不利东北', interp: '艰难跋涉，如涉水登山。前行困难，宜另寻出路，等待时机。' },
            { pattern: 0b001010, num: 40, name: '雷水解', upper: '震', lower: '坎',
                judgment: '利西南，无所往', interp: '困难化解，如春风化冻。烦恼消散，问题解决，雨过天晴。' },
            { pattern: 0b100011, num: 41, name: '山泽损', upper: '艮', lower: '兑',
                judgment: '有孚，元吉，无咎', interp: '损下益上，有失有得。适当减损反而有益，舍小利得大益。' },
            { pattern: 0b110001, num: 42, name: '风雷益', upper: '巽', lower: '震',
                judgment: '利有攸往，利涉大川', interp: '增益丰盈，如春风雨露。好运降临，宜抓住机会积极行动。' },
            { pattern: 0b011111, num: 43, name: '泽天夬', upper: '兑', lower: '乾',
                judgment: '扬于王庭，孚号有厉', interp: '决断果敢，一刀两断。宜果断决策，快刀斩乱麻，不留后患。' },
            { pattern: 0b111110, num: 44, name: '天风姤', upper: '乾', lower: '巽',
                judgment: '女壮，勿用取女', interp: '不期而遇，意外相逢。可能有意外之事发生，需随机应变。' },
            { pattern: 0b011000, num: 45, name: '泽地萃', upper: '兑', lower: '坤',
                judgment: '亨，王假有庙', interp: '聚集荟萃，如江河汇海。人才财物汇聚，宜组织协作。' },
            { pattern: 0b000110, num: 46, name: '地风升', upper: '坤', lower: '巽',
                judgment: '元亨，用见大人', interp: '上升渐进，如幼苗成材。事业逐步上升，循序渐进必成大器。' },
            { pattern: 0b011010, num: 47, name: '泽水困', upper: '兑', lower: '坎',
                judgment: '亨，贞，大人吉', interp: '受困难行，如陷泥沼。处境艰难，但坚守正道终得脱困。' },
            { pattern: 0b010110, num: 48, name: '水风井', upper: '坎', lower: '巽',
                judgment: '改邑不改井，无丧无得', interp: '如井养人，取之不竭。根基稳固，宜修德养民，利他利己。' },
            { pattern: 0b011101, num: 49, name: '泽火革', upper: '兑', lower: '离',
                judgment: '己日乃孚，元亨利贞', interp: '变革革新，如烈火炼金。宜主动求变，革故鼎新，顺势改革。' },
            { pattern: 0b101110, num: 50, name: '火风鼎', upper: '离', lower: '巽',
                judgment: '元吉，亨', interp: '鼎立天下，如烹小鲜。事业稳固，地位确立，功成名就之象。' },
            { pattern: 0b001001, num: 51, name: '震为雷', upper: '震', lower: '震',
                judgment: '亨，震来虩虩', interp: '雷霆震动，如天威降临。突发事件较多，宜镇定从容应对。' },
            { pattern: 0b100100, num: 52, name: '艮为山', upper: '艮', lower: '艮',
                judgment: '艮其背，不获其身', interp: '如山静止，适可而止。宜知止不殆，该停则停，不可贪进。' },
            { pattern: 0b110100, num: 53, name: '风山渐', upper: '巽', lower: '艮',
                judgment: '女归吉，利贞', interp: '循序渐进，如风拂山峦。凡事不可急于求成，按部就班则成。' },
            { pattern: 0b001011, num: 54, name: '雷泽归妹', upper: '震', lower: '兑',
                judgment: '征凶，无攸利', interp: '婚嫁之象，但需两厢情愿。不可强求，名正言顺方为吉。' },
            { pattern: 0b101100, num: 55, name: '雷火丰', upper: '震', lower: '离',
                judgment: '亨，王假之，勿忧', interp: '丰盛盈满，如日中天。事业巅峰，但须知月满则亏。' },
            { pattern: 0b001101, num: 56, name: '火山旅', upper: '离', lower: '艮',
                judgment: '小亨，旅贞吉', interp: '旅行在外，如做客他乡。宜谨慎行事，入乡随俗，平安为上。' },
            { pattern: 0b110110, num: 57, name: '巽为风', upper: '巽', lower: '巽',
                judgment: '小亨，利有攸往', interp: '柔顺谦逊，如微风拂面。以柔克刚，顺从时势可获小成。' },
            { pattern: 0b011011, num: 58, name: '兑为泽', upper: '兑', lower: '兑',
                judgment: '亨，利贞', interp: '喜悦和乐，如湖水荡漾。心情愉悦，人际和谐，宜分享快乐。' },
            { pattern: 0b110010, num: 59, name: '风水涣', upper: '巽', lower: '坎',
                judgment: '亨，王假有庙', interp: '涣散分离，如风吹水面。离散之后重新聚合，宜团结人心。' },
            { pattern: 0b010011, num: 60, name: '水泽节', upper: '坎', lower: '兑',
                judgment: '亨，苦节不可贞', interp: '节制有度，不可过度。凡事适可而止，节制则吉，过则凶。' },
            { pattern: 0b111101, num: 61, name: '风泽中孚', upper: '巽', lower: '兑',
                judgment: '豚鱼吉，利涉大川', interp: '诚信感召，如风过湖面。以诚待人则万物皆应，信誉至上。' },
            { pattern: 0b001100, num: 62, name: '雷山小过', upper: '震', lower: '艮',
                judgment: '亨，利贞，可小事', interp: '小有过越，大事不宜。小事可成，但大事需谨慎，适可而止。' },
            { pattern: 0b010101, num: 63, name: '水火既济', upper: '坎', lower: '离',
                judgment: '亨小，利贞，初吉终乱', interp: '事已成功，但盛极必衰。大功告成后需防懈怠，守成不易。' },
            { pattern: 0b101010, num: 64, name: '火水未济', upper: '离', lower: '坎',
                judgment: '亨，小狐汔济，濡其尾', interp: '事尚未成，功亏一篑。虽未完成但前景可期，继续努力。' },
        ];

const hexagramByPattern = {};
HEXAGRAMS.forEach(h => { hexagramByPattern[h.pattern] = h; });

function tossCoins() {
            const coins = [
                Math.random() < 0.5 ? 3 : 2,
                Math.random() < 0.5 ? 3 : 2,
                Math.random() < 0.5 ? 3 : 2,
            ];
            return coins[0] + coins[1] + coins[2];
        }

function getPattern(lines) {
            let pattern = 0;
            for (let i = 0; i < 6; i++) {
                const val = lines[i];
                const isYang = (val === 7 || val === 9);
                if (isYang) pattern |= (1 << i);
            }
            return pattern;
        }

module.exports = { HEXAGRAMS, hexagramByPattern, tossCoins, getPattern };
